[package]
name = "transient_solar_battery_simulation"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
plotters = "0.3"
iced = { version = "0.14", features = ["canvas"] }
iced_aw = { version = "0.14.1", features = ["number_input", "selection_list"] }
plotters-iced2 = "0.14"

[lints.clippy]
pedantic = {level = "deny", priority = -1}
number_input = {level = "deny", priority = -1}
# DENY PANICS:
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
